
map_layer:
    enabled:              true
    map_topic:            map
    trinary_costmap:      false
    use_maximum:          true
    first_map_only:       true



map_layer:     
    enabled:              true
    map_topic:            map
    trinary_costmap:      true
    use_maximum:          true
    first_map_only:       true

road_layer:
    enabled:              true
    map_topic:            map2
    trinary_costmap:      false
    use_maximum:          true
    first_map_only:       true


global_costmap:
    global_frame: map
    robot_base_frame: robot0
    update_frequency: 5.0
    static_map: true
    publish_frequency: 1.0

    inflation_radius: 1.0
    cost_scaling_factor: 1.0
    map_type: costmap


    plugins:
        - {name: road_layer,              type: "costmap_2d::StaticLayer"}
        - {name: map_layer,               type: "costmap_2d::StaticLayer"}
        - {name: inflation_layer,         type: "costmap_2d::InflationLayer"}
        - {name: grid_layer,              type: "simple_layer_namespace::GridLayer"}

