local_costmap:
    global_frame: robot0 
    robot_base_frame: robot0
    update_frequency: 10.0
    publish_frequency: 10.0
    rolling_window: true
    width: 1.5
    height: 1.5
    resolution: 0.05


    